# Generated by Django 4.1.7 on 2023-03-22 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('client', 'Client'), ('trader', 'Trader')], default='client', max_length=15)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('fruits', 'Fruits'), ('beans', 'Beans'), ('grain', 'Grain'), ('legume', 'Legume'), ('tubers', 'Tubers'), ('diary', 'Dairy'), ('vegetables', 'Vegetables'), ('nuts', 'Nuts&Kernels'), ('animals', 'Animals')], max_length=15)),
                ('price', models.FloatField(default=0.0)),
                ('picture', models.ImageField(upload_to='crop/static/img/')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.agent')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0.0)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.agent')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.product')),
            ],
            options={
                'db_table': 'buy',
            },
        ),
    ]
