# Generated by Django 4.1.7 on 2023-03-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_name', models.CharField(max_length=128, verbose_name='product name')),
                ('stock', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('fruits', 'Fruits'), ('beans', 'Beans'), ('grain', 'Grain'), ('legume', 'Legume'), ('tubers', 'Tubers'), ('diary', 'Dairy'), ('vegetables', 'Vegetables'), ('nuts', 'Nuts&Kernels'), ('animals', 'Animals')], max_length=15)),
                ('unit_price', models.FloatField(default=0.0)),
                ('picture', models.ImageField(upload_to='img/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, null=True, verbose_name='First name')),
                ('last_name', models.CharField(default='', max_length=128, null=True, verbose_name='Last name')),
                ('username', models.CharField(max_length=128, verbose_name='Username')),
                ('contact', models.CharField(max_length=30, verbose_name='Contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country', models.CharField(default='Togo', max_length=60, verbose_name='Country')),
                ('city', models.CharField(default='Lome', max_length=60, verbose_name='City')),
                ('about', models.TextField(default='', max_length=700, null=True, verbose_name='About')),
                ('picture', models.ImageField(upload_to='img/')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crop.user')),
                ('gps', models.CharField(max_length=128, verbose_name='localisation')),
            ],
            options={
                'db_table': 'trader',
            },
            bases=('crop.user',),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('price', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.user')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.product')),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.trader'),
        ),
    ]
